<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="stylediat.css">
</head>
<div class="logout">
<a href="home.php"><img id="back" src="back.svg"></a>
</div>
<body>
<div id="box1">
       <div class="info">
        <h1>12 hour diat</h1>
        <h3>A person needs to decide on and adhere to a 12-hour fasting window every day. According to some researchers, fasting for 10–16 hours can cause the body to turn its fat stores into energy,
         which releases ketones into the bloodstream. This should encourage weight loss</h3>
        </div>
    </div>
    <div id="box2">
       <div class="infolf">
        <h1>lemon juice</h1>
        <h3>It promotes hydration. ...
        It's a good source of vitamin C. ...
        It supports weight loss. ...
        It improves your skin quality. ...
        </h3>
        </div>
    </div>
    <div id="box3">
       <div class="info">
        <h1>beetroot juice</h1>
        <h3>Improved blood flow. Beet juice has a high concentration of natural chemicals known as nitrate. ...
        Lowers blood pressure. ...
        Boosts Stamina. ...
        It detoxifies the liver. ...
        It helps reduce the risk of cancer. ...
        Helps prevent against anemia and iron deficiency. ...
        Helps in building stamina. ...</h3>
        </div>
    </div>
    <div id="box4">
       <div class="infolf">
        <h1>carrot juice</h1>
        <h3>Increased metabolism. ...
        Stronger vision. ...
        Improved skin disorders. ...
        Boosted immune system. ...
        Reduced cancer risk. ...
        Lowered cholesterol. ...
        Healthier pregnancy. ...
        Strengthened brain function.</h3>
        </div>
    </div>
    <div id="box5">
       <div class="infolf">
        <h1>brocoly juice</h1>
        <h3>Vitamin C – builds collagen, which forms body tissue and bone, and helps cuts and wounds heal. Vitamin C is a powerful antioxidant and protects the body from damaging free radicals.
         Fiber – diets high in fiber promote digestive health. A high fiber intake can also help lower cholesterol.</h3>
        </div>
    </div>
    <div id="box6">
       <div class="infolf">
        <h1>orange juice</h1>
        <h3>Rich in Several Important Nutrients. Orange juice is high in many nutrients, including vitamin C, folate, and potassium. ...
        High in Antioxidants. ...
        May Help Prevent Kidney Stones. ...
        May Improve Heart Health. ...</h3>
        </div>
    </div>
    <div id="box7">
       <div class="infolf">
        <h1>guava juice</h1>
        <h3>May Help Lower Blood Sugar Levels. ...
        May Boost Heart Health. ...
        May Help Relieve Painful Symptoms of Menstruation. ...
        May Benefit Your Digestive System. ...
        May Aid Weight Loss. ...</h3>
        </div>
    </div>
    <div id="box8">
       <div class="info">
        <h1>blackberry juice</h1>
        <h3>They're packed with vitamin C. Just one cup of raw blackberries has 30.2 milligrams of vitamin C. ...
        They're high in fiber. Most people don't get enough fiber in their diet. ...
        Great source of vitamin K. ...
        High in manganese. ...
        May boost brain health. ...</h3>
        </div>
    </div>
    <div id="box9">
       <div class="info">
        <h1>watermelon juice</h1>
        <h3>Helps You Hydrate. ...
        Contains Nutrients and Beneficial Plant Compounds. ...
        Contains Compounds That May Help Prevent Cancer. ...
        May Improve Heart Health. ...
        May Lower Inflammation and Oxidative Stress. ...
        May Help Prevent Macular Degeneration. ...</h3>
        </div>
    </div>
    <div id="box10">
       <div class="info">
        <h1>coconut water</h1>
        <h3>Good Source of Several Nutrients. Share on Pinterest. ...
        May Have Antioxidant Properties. ...
        May Have Benefits Against Diabetes. ...
        May Help Prevent Kidney Stones. ...
        May Support Heart Health. ...
        May Reduce Blood Pressure. ...</h3>
        </div>
    </div>
    <div id="box11">
       <div class="info">
        <h1>strowberry juice</h1>
        <h3>The juicy fruit is also rich in vital minerals, such as potassium and phytonutrients—these sweet, yet tangy berries are wonderful when added to smoothies. A glass of 
        strawberry juice will provide your body with immune-boosting power and properties of polyphenols and antioxidants.</h3>
        </div>
    </div>
</body>
